[package]
name = "media-controller"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
enigo = "0.5.0"
mpris = "2.0.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
souvlaki = { version = "0.8.3", default-features = false, features = ["use_zbus"]}
