# GitHub Actions workflow: auto-tag, build, and publish release

# Automatically bumps semantic version (patch) on push to main, then publishes a release and upload binary.

name: Auto Tag and Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag-and-release:
  runs-on: ubuntu-latest
  permissions:
    contents: write
  steps:
    - name: Checkout repository
      uses: actions/checkout\@v3
      with:
      fetch-depth: 0   # fetch all history for semver

    - name: Bump version and create tag
      id: tag
      uses: anothrNick/github-tag-action@v1.37.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        version_prefix: "v"

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Build release
      run: cargo build --release

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.new_tag }}
        release_name: ${{ steps.tag.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Upload release binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/release/media-controller
        asset_name: media-controller
        asset_content_type: application/octet-stream

